### ISSUE TITLE
welcome page renewal

### ISSUE THREAD

**Issue by yo0oni** [SiliconValley22-Blossom/frontend#47]

**Comment by phjppo0918** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/55674648/180595234-f09628e5-29aa-4abe-82a0-0819d2e1d0d5.png">
가운데 버튼 호버시
<img width="572" alt="image" src="https://user-images.githubusercontent.com/55674648/180595269-3c95f9f6-6b66-4541-a5f1-de578e896c4b.png">

중앙에 로고 들어가야 하는 것 인지
